#!/bin/bash

cd /

function screenResize {
   #scrnW=$(xrandr | grep "\." | awk -F 'x' '{print $1}' | sort -nr  | head -1)
   scrnW=$(xrandr | grep "\." | awk -F 'x' '{print $1}' | head -1)
   #scrnH=$(xrandr | grep "\." | awk -F 'x' '{print $2}' | awk '{print $1}' | sort -nr | head -1)
   scrnH=$(xrandr | grep "\." | awk -F 'x' '{print $2}' | awk '{print $1}' | head -1)
   # get info from xrandr
   connectedOutputs=$(xrandr | grep " connected" | sed -e "s/\([A-Z0-9]\+\) connected.*/\1/")
   activeOutput=$(xrandr | grep -E " connected (primary )?[1-9]+" | sed -e "s/\([A-Z0-9]\+\) connected.*/\1/")
   dspl_nm=$(xrandr -q | grep -w "connected" | wc -l)

   # initialize variables
   execute="xrandr "
   default="xrandr "
   i=1
   switch=0

   if [ $dspl_nm -eq 1 ] 
   then
	default=$default"--output $connectedOutputs --auto"
	#default=$default"--output $connectedOutputs --mode $scrnW""x""$scrnH --rate 60"
	$default
   else
	for display in $connectedOutputs
	do
		# build default configuration
		if [ $i -eq 1 ]
		then
			default=$default"--output $display --auto"
			#default=$default"--output $display --mode $scrnW""x""$scrnH --rate 60"

		else
			default=$default"--output $display --off "
		fi

		# build "switching" configuration
		if [ $switch -eq 1 ]
		then
			execute=$execute"--output $display  --auto"
			#execute=$execute"--output $display  --mode $scrnW""x""$scrnH --rate 60"
			switch=0
		else
			execute=$execute"--output $display --off "
		fi

		# check whether the next output should be switched on
		if [ $display = $activeOutput ]
		then
			switch=1
		fi

		i=$(( $i + 1 ))
	done
	# check if the default setup needs to be executed then run it
	if [ -z "$(echo $execute | grep "auto")" ]
	then
		`$default`
	else
		`$execute`
	fi
   fi
}

crntW=$(xrandr | grep "\." | awk -F 'x' '{print $1}' | head -1)
crntH=$(xrandr | grep "\." | awk -F 'x' '{print $2}' | awk '{print $1}' | head -1)

screenResize
while :
do
#echo "crntW $crntW"
#echo "crntH $crntH"
   #tmpW=$(xrandr | grep "\." | awk -F 'x' '{print $1}' | sort -nr  | head -1)
   #tmpH=$(xrandr | grep "\." | awk -F 'x' '{print $2}' | awk '{print $1}' | sort -nr | head -1)
   tmpW=$(xrandr | grep "\." | awk -F 'x' '{print $1}' | head -1)
   tmpH=$(xrandr | grep "\." | awk -F 'x' '{print $2}' | awk '{print $1}' | head -1)
#echo "tmpW $tmpW"
#echo "tmpH $tmpH"

   if [[ "$tmpW" -ne "$crntW" ]] && [[ "$tmpH" -ne "$crntH" ]]
   then
      screenResize

      crntW=$tmpW
     # echo "widht $scrntW"
      crntH=$tmpH
     # echo "height $scrntH"
   elif [[ "$tmpW" -ne "$crntW" ]]
   then
      screenResize

      crntW=$tmpW
   elif [[ "$tmpH" -ne "$crntH" ]]
   then
      screenResize

      crntH=$tmpH
   fi
done
